### PR TITLE
Initial groundwork for Keybase Gem

### PR DESCRIPTION
**Pull request by seanhandley**
[Build Status](http://travis-ci.org/seanhandley/keybase)
- [x] Wrap Faraday as a request object base class
- [x] Make a basic user data object
- [x] Implement a simple user lookup function
- [x] Handle Keybase API errors accordingly
- [x] Basic integration tests
- [x] Travis CI
- [x] Parse all user data into User object
- [x] Implement 2-stage login via getsalt and scrypt
- [x] Find a clean way to share the CSRF token across calls
- [x] Implement key add/revoke
- [x] Implement post_auth
- [x] Implement dump all/latest
- [x] Finish Unit tests
- [x] Integration tests for keys
- [x] Integration tests for dumps
- [x] YARD doc

### CODE REVIEW

**Comment by seanhandley** [comment]
@maxtaco Let me know if you have any thoughts on this as an approach to structuring the gem - comments welcome!

**Comment by maxtaco** [comment]
@seanhandley , this looks great, we're so happy that you working on it.

We were thinking about the best way to proceed. Maybe keep hacking over in your repo, and we'll merge you over and add you as a contributor when you get a little bit further?

Many thanks!

**Comment by seanhandley** [comment]
Sure thing @maxtaco - I want to stabilise the test environment (the Mocha gem is behaving strangely at the moment).

After that I'll start working on more complex functions like `get_salt` and `login` and see how well they work with the Scrypt gem.

**Comment by seanhandley** [comment]
Perhaps you can give me a hand @maxtaco ?

I'm trying to use authenticated API methods (in this case, `sig/post_auth`.

Can you give me an idea what a request ought to look like?

Here's my current debug info. You can't see, but the request contains the correct form params i.e.

``` ruby
{'sig' => 'signature', 'email_or_username' => 'seanhandley', 'csrf-token' => 'session_token'}
```

```
I, [2014-03-24T17:11:51.405358 #35786]  INFO -- : get https://keybase.io/_/api/1.0/getsalt.json?email_or_username=seanhandley
D, [2014-03-24T17:11:51.405482 #35786] DEBUG -- request: User-Agent: "Faraday v0.9.0"
I, [2014-03-24T17:11:52.360040 #35786]  INFO -- Status: 200
D, [2014-03-24T17:11:52.360276 #35786] DEBUG -- response: server: "nginx/1.4.3"
date: "Mon, 24 Mar 2014 17:11:27 GMT"
content-type: "application/json; charset=utf-8"
content-length: "428"
connection: "close"
x-powered-by: "Express"
strict-transport-security: "max-age=31536000"
set-cookie: "guest=lgHZIDQ0ZWUxMzI1NjE3NzYyMmY4YmU5YmU2MTE2MGQwYzA4zlMwZz%2FOAAFRgMDEIBXG%2FMCokdxOYmrLjujnMfIExg1aHqPhMMHZMNX6K5rQ; Max-Age=604.8; Domain=.keybase.io; Path=/; Expires=Mon, 24 Mar 2014 17:21:32 GMT; HttpOnly; Secure"
expires: "-1"
cache-control: "must-revalidate, private"
etag: "\"-1314681789\""
I, [2014-03-24T17:11:52.519082 #35786]  INFO -- : post https://keybase.io/_/api/1.0/login.json
D, [2014-03-24T17:11:52.519191 #35786] DEBUG -- request: CSRF-Token: "lgHZIGU3MjBmNWE0Y2NlOWM2MGY5NDUzOGQzMDk1OWU3MTAwzlMwZz/NASzAxCALMl4XerKEYf4f9ux6o2eLp16dqxJfRUO2xXm/aj2ezQ=="
User-Agent: "Faraday v0.9.0"
Content-Type: "application/x-www-form-urlencoded"
I, [2014-03-24T17:11:53.069509 #35786]  INFO -- Status: 200
D, [2014-03-24T17:11:53.069655 #35786] DEBUG -- response: server: "nginx/1.4.3"
date: "Mon, 24 Mar 2014 17:11:28 GMT"
content-type: "application/json; charset=utf-8"
content-length: "14299"
connection: "close"
x-powered-by: "Express"
strict-transport-security: "max-age=31536000"
set-cookie: "guest=lgHZIDVmMjliOTA3OTlkY2U5M2E2N2NlNTZkZGEwNDEwNDA4zlMwZ0DOAAFRgMDEIB82Gz5syaX38poj2p6XrQOiVzPUaPqtz4Wi9kQe6T7E; Max-Age=604.8; Domain=.keybase.io; Path=/; Expires=Mon, 24 Mar 2014 17:21:33 GMT; HttpOnly; Secure, session=lgHZIGU3MjBmNWE0Y2NlOWM2MGY5NDUzOGQzMDk1OWU3MTAwzlMwZ0DOAeEzgNkgNzhjYWMyYjVkNjIxNjM0MDE4NGEyODZkYmM2MWI2MDLEIL8DNMxU1HN0GzfQF7%2FT9OrjYB1rltVvTbeDMM4V%2Flqg; Max-Age=31536000; Domain=.keybase.io; Path=/; Expires=Tue, 24 Mar 2015 17:11:28 GMT; HttpOnly; Secure"
 => true 
2.1.0p0 :003 > @me.post_auth('foo')
I, [2014-03-24T17:11:56.019400 #35786]  INFO -- : post https://keybase.io/_/api/1.0/sig/post_auth.json
D, [2014-03-24T17:11:56.019634 #35786] DEBUG -- request: Cookie: "guest=lgHZIDVmMjliOTA3OTlkY2U5M2E2N2NlNTZkZGEwNDEwNDA4zlMwZ0DOAAFRgMDEIB82Gz5syaX38poj2p6XrQOiVzPUaPqtz4Wi9kQe6T7E; Max-Age=604.8; Domain=.keybase.io; Path=/; Expires=Mon, 24 Mar 2014 17:21:33 GMT; HttpOnly; Secure, session=lgHZIGU3MjBmNWE0Y2NlOWM2MGY5NDUzOGQzMDk1OWU3MTAwzlMwZ0DOAeEzgNkgNzhjYWMyYjVkNjIxNjM0MDE4NGEyODZkYmM2MWI2MDLEIL8DNMxU1HN0GzfQF7%2FT9OrjYB1rltVvTbeDMM4V%2Flqg; Max-Age=31536000; Domain=.keybase.io; Path=/; Expires=Tue, 24 Mar 2015 17:11:28 GMT; HttpOnly; Secure"
CSRF-Token: "lgHZIGU3MjBmNWE0Y2NlOWM2MGY5NDUzOGQzMDk1OWU3MTAwzlMwZz/NASzAxCALMl4XerKEYf4f9ux6o2eLp16dqxJfRUO2xXm/aj2ezQ=="
User-Agent: "Faraday v0.9.0"
Content-Type: "application/x-www-form-urlencoded"
I, [2014-03-24T17:11:56.605763 #35786]  INFO -- Status: 200
D, [2014-03-24T17:11:56.605970 #35786] DEBUG -- response: server: "nginx/1.4.3"
date: "Mon, 24 Mar 2014 17:11:31 GMT"
content-type: "application/json; charset=utf-8"
content-length: "240"
connection: "close"
x-powered-by: "Express"
strict-transport-security: "max-age=31536000"
{"status"=>{"code"=>222, "desc"=>"CSRF-token verification failed for post", "name"=>"CSRF"}, "csrf_token"=>"lgHZIGU3MjBmNWE0Y2NlOWM2MGY5NDUzOGQzMDk1OWU3MTAwzlMwZ0DOAAFRgMDEIBkW64WcuhRRek9M6Br8BgMV3ur6q2jqPeZf8+FwTC6I"}
Keybase::Error: Error 222: CSRF-token verification failed for post
    from /Users/sean/.rvm/gems/ruby-2.1.0/gems/keybase-0.0.0/lib/keybase/error.rb:10:in `raise_unless_successful'
    from /Users/sean/.rvm/gems/ruby-2.1.0/gems/keybase-0.0.0/lib/keybase/response.rb:10:in `initialize'
    from /Users/sean/.rvm/gems/ruby-2.1.0/gems/keybase-0.0.0/lib/keybase/request/base.rb:11:in `new'
    from /Users/sean/.rvm/gems/ruby-2.1.0/gems/keybase-0.0.0/lib/keybase/request/base.rb:11:in `post'
    from /Users/sean/.rvm/gems/ruby-2.1.0/gems/keybase-0.0.0/lib/keybase/request/sig/post_auth.rb:8:in `post_auth'
    from /Users/sean/.rvm/gems/ruby-2.1.0/gems/keybase-0.0.0/lib/keybase/models/user.rb:32:in `post_auth'
    from (irb):3
    from /Users/sean/.rvm/rubies/ruby-2.1.0/bin/irb:11:in `<main>'
2.1.0p0 :004 > 
```

**Comment by maxtaco** [comment]
Try sending the CSRF token as an HTTP header, with `X-CSRF-Token: <token>`?

**Comment by seanhandley** [comment]
Same issuse. You can see the token near the top:

```
I, [2014-03-24T20:17:09.234039 #36512]  INFO -- : post https://keybase.io/_/api/1.0/sig/post_auth.json
D, [2014-03-24T20:17:09.234278 #36512] DEBUG -- request: Cookie: "guest=lgHZIGFlNThjNzViNWI2Yzg4NzhkNTEzOGVjNGZiNGJkNzA4zlMwkqjOAAFRgMDEIFJPLGU4n12J3%2BuJROa%2BWMsRrWBxUZ%2F4zb04bbPJuijr; Max-Age=604.8; Domain=.keybase.io; Path=/; Expires=Mon, 24 Mar 2014 20:26:45 GMT; HttpOnly; Secure, session=lgHZIGU3MjBmNWE0Y2NlOWM2MGY5NDUzOGQzMDk1OWU3MTAwzlMwkqjOAeEzgNkgMmM2NGJlMjhlMDg0NGRjZjY3ZmQ3NmQxZDQ1MThiMDLEIEc9bGev4U2XscpYGedvTLCcYzHbV4LapsvuX9OzKCZX; Max-Age=31536000; Domain=.keybase.io; Path=/; Expires=Tue, 24 Mar 2015 20:16:40 GMT; HttpOnly; Secure"
X-CSRF-Token: "lgHZIGU3MjBmNWE0Y2NlOWM2MGY5NDUzOGQzMDk1OWU3MTAwzlMwkqfNASzAxCA5WMDcU11XqWSV4f6HsvVVMCsLrxnlPQWMWUtCm2EaAw=="
User-Agent: "Faraday v0.9.0"
Content-Type: "application/x-www-form-urlencoded"
I, [2014-03-24T20:17:09.979704 #36512]  INFO -- Status: 200
D, [2014-03-24T20:17:09.979875 #36512] DEBUG -- response: server: "nginx/1.4.3"
date: "Mon, 24 Mar 2014 20:16:44 GMT"
content-type: "application/json; charset=utf-8"
content-length: "240"
connection: "close"
x-powered-by: "Express"
strict-transport-security: "max-age=31536000"
{"status"=>{"code"=>222, "desc"=>"CSRF-token verification failed for post", "name"=>"CSRF"}, "csrf_token"=>"lgHZIGU3MjBmNWE0Y2NlOWM2MGY5NDUzOGQzMDk1OWU3MTAwzlMwkqjOAAFRgMDEIOsTlUxeFoQjH19PZr7uKUcaOpm6D3hnQxUodZc8nrE1"}
Keybase::CSRFVerificationError: CSRF-token verification failed for post
    from /Users/sean/.rvm/gems/ruby-2.1.0/gems/keybase-0.0.0/lib/keybase/error.rb:8:in `raise_unless_successful'
    from /Users/sean/.rvm/gems/ruby-2.1.0/gems/keybase-0.0.0/lib/keybase/response.rb:10:in `initialize'
    from /Users/sean/.rvm/gems/ruby-2.1.0/gems/keybase-0.0.0/lib/keybase/request/base.rb:11:in `new'
    from /Users/sean/.rvm/gems/ruby-2.1.0/gems/keybase-0.0.0/lib/keybase/request/base.rb:11:in `post'
    from /Users/sean/.rvm/gems/ruby-2.1.0/gems/keybase-0.0.0/lib/keybase/request/sig/post_auth.rb:8:in `post_auth'
    from /Users/sean/.rvm/gems/ruby-2.1.0/gems/keybase-0.0.0/lib/keybase/models/user.rb:32:in `post_auth'
    from (irb):3
    from /Users/sean/.rvm/rubies/ruby-2.1.0/bin/irb:11:in `<main>'
2.1.0p0 :004 > 
```

Perhaps I should take a look at the node client code?

**Comment by maxtaco** [comment]
The CSRF token you're sending looks like a login_session.  For one, it expires after 300s, whereas CSRF tokens expire after 86,400s.  So I think that's what's going on here.

**Comment by seanhandley** [comment]
Ahh yes that was it - it's working properly now.

Thanks!

**Comment by maxtaco** [comment]
w00t!

**Comment by seanhandley** [comment]
Would be awesome if the API documentation specifically mentioned that the 'Cookie' and 'X-CSRF-Token' headers need to be set :+1:

**Comment by seanhandley** [comment]
@maxtaco Can you please explain how (and why) you'd use `sig/post_auth` ?

**Comment by maxtaco** [comment]
It's an alternative authentication mechanism.  Instead of PW authentication, you can establish a session by signing a login token with your private key.  Do you think you have a need for this?  We thought at first we'd use it but wound up not.  The features work and check out in our regression tests but aren't well-documented.

**Comment by seanhandley** [comment]
I was basically planning to include integration tests for it for completeness.

If it's not really used then I think I'll leave it out for now.

**Comment by seanhandley** [comment]
@maxtaco @malgorithms I'm about all done now. Ready to merge.

Let me know if you guys have any questions/concerns!

**Comment by seanhandley** [comment]
PS I can squash the commits into a single commit if you prefer it that way.

**Comment by maxtaco** [comment]
Hi Sean, I read through the code, it looks really good so far, great job.  As to how we should proceed, what do you think about merging this work into another repo called something like `keybase/ruby-lib` available as the gem 'keybase-lib'? I'm just hesitant to call this gem 'keybase' in its current form since it doesn't function as a command-line client.

**Comment by seanhandley** [comment]
Yeah that's absolutely fine with me.

How about `keybase-core` ? Then we can easily wrap it as CLI tool afterwards.

**Comment by seanhandley** [comment]
Just let me know when you have a repository created and I'll open a fresh pull request against it.

**Comment by maxtaco** [comment]
You should be able to push to `keybase/ruby-core` now.  Let me know if not.  Thanks Sean!

**Comment by seanhandley** [comment]
I can see it but I can't push to it.

I can make a new PR though!

**Comment by maxtaco** [comment]
Permissions too tight.  Try it again?  Thanks.

**Comment by seanhandley** [comment]
Great - that's working. Thanks @maxtaco 

Could you sign into https://travis-ci.org with Github and activate the CI for the repo? You need to be an organisation member I think.

**Pull request closed without merging**
